package com.kite.engine.event;

public enum EventType
{
    KEY_PRESSED, KEY_RELEASED,
    MOUSE_BUTTON_PRESSED, MOUSE_BUTTON_RELEASED, MOUSE_SCROLLED, MOUSE_MOVED,
    WINDOW_RESIZED, WINDOW_CLOSED,
    APPLICATION_INITIALIZED, APPLICATION_STARTED, APPLICATION_STOPPED,
    SCENE_STARTED, SCENE_STOPPED, SCENE_ENDED,
    ENTITY_CREATED, ENTITY_COMPONENT_ADDED, ENTITY_COMPONENT_REMOVED, ENTITY_DELETED
}
